### ISSUE TITLE
Build failing when installing berkshelf

### ISSUE THREAD

**Issue by Red5d** [whithajess/DockerNexpose#2]
The build is failing with the following error:

    ERROR:  Error installing berkshelf:
	    ERROR: Failed to build gem native extension.

**Comment by whithajess** [comment]
Hey Sorry only just noticed this Issue! I just ran this through with no problems. I take it this was fixed by f791e2eafbd5e58ea99ee4c1a13addb18be17570 if you pull down the latest code and run it again you should have no problems.
