### ISSUE TITLE
No Berksfile or Berksfile.lock found at '/chef'!

### ISSUE THREAD

**Issue by RvdGijp** [whithajess/DockerNexpose#3]
Step 8 : RUN cd /chef && /opt/chef/embedded/bin/berks vendor /chef/cookbooks
No Berksfile or Berksfile.lock found at '/chef'!
The command '/bin/sh -c cd /chef && /opt/chef/embedded/bin/berks vendor /chef/cookbooks' returned a non-zero code: 100

**Comment by RvdGijp** [comment]
The Berkfile was not copied.

**Comment by whithajess** [comment]
Was this still a problem or did it just resolve itself?

**Comment by RvdGijp** [comment]
It was clumsiness of me :-)
No, it was not a problem.

**Comment by whithajess** [comment]
Sweet =)
