### ISSUE TITLE
No Berksfile or Berksfile.lock found at '/chef'!

### ISSUE THREAD

**Issue by qjax** [whithajess/DockerNexpose#6]
First I tried to build from OS X 10.11.2 using Docker Kitematic 0.9.5 - Docker 1.9.1.  Although the container came up, Nexpose ports were not exposed.  Running _Docker attached $[ImageID] _ appeared to hang or not allow me to type inside container.

Decided to run directly from command line on Ubuntu 15.04.  I copy/pasted Dockerfile and ran:
_**Docker build .**_  to watch the build process fail at **Step 9**.

Step 9 : RUN cd /chef && /opt/chef/embedded/bin/berks vendor /chef/cookbooks
 ---> Running in c71148464a9c
**No Berksfile or Berksfile.lock found at '/chef'!**
The command '/bin/sh -c cd /chef && /opt/chef/embedded/bin/berks vendor /chef/cookbooks' returned a non-zero code: 

--------------------------------------------------------------------------------------------------
**Step 5 : **RUN curl -L https://www.opscode.com/chef/install.sh | sudo bash
 ---> Running in aa0652c4c3cb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20022  100 20022    0     0  38662      0 --:--:-- --:--:-- --:--:-- 38727
Getting information for chef stable  for ubuntu...
downloading https://omnitruck-direct.chef.io/stable/chef/metadata?v=&p=ubuntu&pv=14.04&m=x86_64
  to file /tmp/install.sh.8/metadata.txt
trying curl...
url	https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/14.04/x86_64/chef_12.6.0-1_amd64.deb
md5	5cfc19d5a036b3f7860716bc9795a85e
sha256	e0b42748daf55b5dab815a8ace1de06385db98e29a27ca916cb44f375ef65453
version	12.6.0downloaded metadata file looks valid...
downloading https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/14.04/x86_64/chef_12.6.0-1_amd64.deb
  to file /tmp/install.sh.8/chef_12.6.0-1_amd64.deb
trying curl...
Comparing checksum with sha256sum...

WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

You are installing an omnibus package without a version pin.  If you are installing
on production servers via an automated process this is DANGEROUS and you will
be upgraded without warning on new releases, even to new major releases.
Letting the version float is only appropriate in desktop, test, development or
CI/CD environments.

WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

Installing chef 
installing with dpkg...
Selecting previously unselected package chef.
(Reading database ... 18670 files and directories currently installed.)
Preparing to unpack .../chef_12.6.0-1_amd64.deb ...
Unpacking chef (12.6.0-1) ...
Setting up chef (12.6.0-1) ...
Thank you for installing Chef!
 ---> f9bd49379ec1
Removing intermediate container aa0652c4c3cb
**Step 6 :** RUN echo "gem: --no-ri --no-rdoc" > ~/.gemrc
 ---> Running in b8a5743f4f4e
 ---> 5e0c89cf6c0b
Removing intermediate container b8a5743f4f4e
**Step 7 : **RUN /opt/chef/embedded/bin/gem install berkshelf
 ---> Running in 7df6a8375f0b
Successfully installed httpclient-2.6.0.1
Successfully installed berkshelf-api-client-2.0.0
Successfully installed buff-extensions-1.0.0
Successfully installed varia_model-0.4.1
Successfully installed buff-config-1.0.1
Successfully installed buff-ruby_engine-0.1.0
Successfully installed buff-shell_out-0.2.0
Building native extensions.  This could take a while...
Successfully installed hitimes-1.2.3
Successfully installed timers-4.0.4
Successfully installed celluloid-0.16.0
Building native extensions.  This could take a while...
Successfully installed nio4r-1.2.0
Successfully installed celluloid-io-0.16.2
Successfully installed cleanroom-1.0.0
Successfully installed minitar-0.5.4
Successfully installed octokit-3.8.0
Successfully installed retryable-2.0.3
Successfully installed buff-ignore-1.1.1
Successfully installed semverse-1.2.1
Successfully installed ridley-4.4.2
Building native extensions.  This could take a while...
Successfully installed dep-selector-libgecode-1.0.2
Building native extensions.  This could take a while...
Successfully installed dep_selector-1.0.3
Successfully installed solve-1.2.1
Successfully installed thor-0.19.1
Successfully installed berkshelf-4.0.1
24 gems installed
 ---> 82e5c718a4c3
Removing intermediate container 7df6a8375f0b
**Step 8 : **ADD . /chef
 ---> 6287ec78d482
Removing intermediate container 9cdda36dbf0c
**Step 9 : RUN cd /chef && /opt/chef/embedded/bin/berks vendor /chef/cookbooks**
 ---> Running in c71148464a9c
No Berksfile or Berksfile.lock found at '/chef'!
The command '/bin/sh -c cd /chef && /opt/chef/embedded/bin/berks vendor /chef/cookbooks' returned a non-ze

**Comment by whithajess** [comment]
Hi there @qjax, sorry about the slow reply copy and pasting the Dockerfile will not work as if you read it you will see it depends on the other files in the git project. So I suggest if you want to build the image you clone the whole directory. Alternatively you can try the docker instructions where the image is already built for you.
