### ISSUE TITLE
Can't connect on the mapped port

### ISSUE THREAD

**Issue by dmerrick** [whithajess/DockerNexpose#7]
On the host machine:

```
➔ curl -vLk https://localhost:49160/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 49160 (#0)
* Internal SSL engine error encountered during the SSL handshake
* Curl_http_done: called premature == 1
* Closing connection 0
curl: (35) Internal SSL engine error encountered during the SSL handshake
```

If I run the same command in the container, I get a successful response

**Comment by whithajess** [comment]
I will test this now but can you confirm you followed the instructions as specified in the readme? as the flag `-p 49160:3780` should map your localhost port to the container port of `3780` it shouldn't give you a successful response with curling to that port from your host. Can you also confirm your version of docker?

**Comment by dmerrick** [comment]
Yeah, I did it exactly as in the README. (I actually changed it to `-p 3780:3780` so it would be easier to remember, but it doesn't work either way).

```
➔ docker -v
Docker version 1.13.1, build 092cba3
```

I also tried editing `conf/httpd.xml` in the `nsc` dir on the container, to listen on `0.0.0.0` instead of `127.0.0.1`, but this didn't fix it.

**Comment by whithajess** [comment]
Hey so I followed the exact instructions `docker pull whithajess/dockernexpose` and then `sudo docker run \
  --name nexpose_container \
  -p 49160:3780 \
  -d whithajess/dockernexpose` and it works fine for me I am also using the exact same docker version and build as you. The only suggestions I can give is to look into proxy/network config on your host that may be messing with this. Also to note is it takes a while to actually start up after doing the `docker run` so you may have to give it more time.
